name: terraform-apply

on:
  pull_request:
    branches:
      - master

env:
  TF_VERSION: 1.0.2
  REGION: eu-central-1
  GO_VERSION: 1.15.8

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform apply

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build app
        run: make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Terraform Init
        run: terraform init -backend-config=config/config.remote
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
